### ISSUE TITLE
Example in the readme needs tweaking

### ISSUE THREAD

**Issue by srfraser** [jacobmarshall/go-toast#1]
Lines 15 and 16 need modifying in order to build.

Using go 1.6.3 and:
```
        Actions: []toast.Action{
            {"protocol", "I'm a button"},
            {"protocol", "Me too!"},
        },
```
I get:
```
.\main.go:15: too few values in struct initializer
.\main.go:16: too few values in struct initializer
```

Adding in the `Arguments` string worked:
```
        Actions: []toast.Action{
            {"protocol", "I'm a button", ""},
            {"protocol", "Me too!", ""},
        },
```

**Comment by jacobmarshall** [comment]
Ah silly me, thanks for spotting that. I'll fix it shortly.

**Comment by srfraser** [comment]
Thank you! Very useful library.

Just discovered that if the Icon is not a full path, then you don't get shown the message or buttons, either (probably obvious for some folks, but I didn't know, so I'm writing it down where people may find it)

**Comment by jacobmarshall** [comment]
Thanks for the feedback. I'll make sure to write some proper docs at some stage, but I'm glad you like it 😊
